import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || process.env.NEXTAUTH_URL || "https://cumi.dev";
  
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/about_us",
          "/our_services",
          "/our_services/*",
          "/contact_us",
          "/blog_posts",
          "/blog_posts/*",
          "/projects",
          "/projects/*",
          "/events",
          "/events/*",
          "/courses",
          "/courses/*",
          "/opportunities",
          "/opportunities/*",
          "/partners",
          "/partners/*",
          "/categories",
          "/categories/*",
          "/tags",
          "/tags/*",
          "/authors",
          "/authors/*",
          "/faqs",
          "/login",
          "/register",
          "/forgot-password",
          "/auth/reset-password",
        ],
        disallow: [
          "/dashboard",
          "/dashboard/*",
          "/api",
          "/api/*",
          "/admin",
          "/admin/*",
          "/private-*",
          "/_next",
          "/_next/*",
          "/uploads/*",
          "/student/*",
          "/dashboard/student/*",
          "/dashboard/creator/*",
          "/dashboard/admin/*",
        ],
        crawlDelay: 1,
      },
      // Special rule for Google
      {
        userAgent: "Googlebot",
        allow: [
          "/",
          "/about_us",
          "/our_services",
          "/our_services/*",
          "/contact_us",
          "/blog_posts",
          "/blog_posts/*",
          "/projects",
          "/projects/*",
          "/events",
          "/events/*",
          "/courses",
          "/courses/*",
          "/opportunities",
          "/opportunities/*",
          "/partners",
          "/partners/*",
          "/categories",
          "/categories/*",
          "/tags",
          "/tags/*",
          "/authors",
          "/authors/*",
          "/faqs",
        ],
        disallow: [
          "/dashboard",
          "/dashboard/*",
          "/api",
          "/api/*",
          "/admin",
          "/admin/*",
          "/private-*",
          "/_next",
          "/_next/*",
          "/uploads/*",
        ],
        crawlDelay: 0.5,
      },
      // Special rule for Bingbot
      {
        userAgent: "Bingbot",
        allow: [
          "/",
          "/about_us",
          "/our_services",
          "/our_services/*",
          "/contact_us",
          "/blog_posts",
          "/blog_posts/*",
          "/projects",
          "/projects/*",
          "/events",
          "/events/*",
          "/courses",
          "/courses/*",
        ],
        disallow: [
          "/dashboard",
          "/dashboard/*",
          "/api",
          "/api/*",
          "/admin",
          "/admin/*",
          "/private-*",
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}